// 100 starter dishes for the seed (P0-14). Data only — consumed by generate.mjs,
// which validates every dish against the schema + recommendation-engine rules
// (diet coherence, allergen presence, activation checklist) before emitting SQL.
//
// Factory args:
//   d(name, cuisine, diet, slots, prepMin, cookMin, difficulty, spice, flags,
//     ingredients, opts)
//   - diet      ∈ diet_type        (vegetarian|vegan|eggetarian|non_vegetarian|jain|pescatarian)
//   - slots     ⊆ meal_slot        (breakfast|lunch|dinner|snack)
//   - difficulty∈ difficulty_level  (easy|medium|hard)
//   - spice     ∈ spice_level       (mild|medium|spicy)
//   - flags     ⊆ kid_friendly|lunchbox_friendly|leftover_friendly|
//                 batch_cook_friendly|diabetic_friendly|low_sodium|
//                 high_protein|low_carb
//   - ingredients: [name, qtyPerServing, unit, required?]  (required defaults true)
//   - opts: { region, desc, prepTasks: [[task, requiredBeforeMin, desc?]],
//             pairings: [[pairedDishName, pairing_type]] }
//             pairing_type ∈ main_side|rice_pairing|bread_pairing|condiment|beverage

const d = (
  name,
  cuisine,
  diet,
  slots,
  prep,
  cook,
  difficulty,
  spice,
  flags,
  ingredients,
  opts = {},
) => ({
  name,
  cuisine,
  diet,
  slots,
  prep,
  cook,
  difficulty,
  spice,
  flags,
  ingredients,
  prepTasks: opts.prepTasks ?? [],
  pairings: opts.pairings ?? [],
  region: opts.region ?? null,
  desc: opts.desc ?? null,
});

/**
 * Dish meal-role overrides (BUG-008/009/010). A dish's `meal_role` decides
 * whether it may stand alone as a primary recommendation: only `complete_meal`
 * and `main_component` may; rice/bread components, sides, condiments, and
 * beverages appear only as pairings of a main. Anything not listed here defaults
 * to `main_component` (the safe, standalone-eligible role). Keep this aligned with
 * the engine's standalone hard filter (lib/recommendation/hard-filters.ts).
 */
export const MEAL_ROLE_OVERRIDES = {
  // Plain rice — only as a rice pairing.
  "Steamed Rice": "rice_component",
  "Jeera Rice": "rice_component",
  // Plain breads — only as a bread pairing.
  Roti: "bread_component",
  "Tandoori Roti": "bread_component",
  "Butter Naan": "bread_component",
  Bhature: "bread_component",
  // Chutneys / dips — accompaniments, never a meal.
  "Coconut Chutney": "condiment",
  "Mint Chutney": "condiment",
  // Sides — need a main to be a meal.
  "Boondi Raita": "side",
  "Jeera Aloo": "side",
  // Beverage.
  "Masala Chai": "beverage",
  // Self-contained one-pot meals.
  "Veg Pulao": "complete_meal",
  "Jain Vegetable Pulao": "complete_meal",
  "Vegetable Biryani": "complete_meal",
  "Chicken Biryani": "complete_meal",
  "Bisi Bele Bath": "complete_meal",
  "Lemon Rice": "complete_meal",
  "Curd Rice": "complete_meal",
  "Ven Pongal": "complete_meal",
  "Sabudana Khichdi": "complete_meal",
  "Egg Fried Rice": "complete_meal",
  "Veg Fried Rice": "complete_meal",
  "Prawn Fried Rice": "complete_meal",
  "Veg Hakka Noodles": "complete_meal",
  "Pasta Arrabbiata": "complete_meal",
  "Pasta Alfredo": "complete_meal",
  "Rajma Quinoa Bowl": "complete_meal",
  // One-pot rice + lentil meal.
  Khichdi: "complete_meal",
  // Accompaniments — need a main to be a meal (BUG-014 required-dish set).
  "Mango Pickle": "condiment",
  Papad: "side",
  Raita: "side",
  "Green Salad": "side",
};

export const DISHES = [
  // ── North Indian curries & dals ─────────────────────────────────────────────
  d(
    "Dal Tadka",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    10,
    25,
    "easy",
    "medium",
    ["leftover_friendly", "batch_cook_friendly", "high_protein"],
    [
      ["Toor Dal", 60, "g"],
      ["Onion", 40, "g"],
      ["Tomato", 50, "g"],
      ["Garlic", 5, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Turmeric", 0.5, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      desc: "Yellow lentils tempered with cumin, garlic and ghee.",
      pairings: [["Jeera Rice", "rice_pairing"]],
    },
  ),

  d(
    "Rajma Masala",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    15,
    40,
    "medium",
    "medium",
    ["leftover_friendly", "batch_cook_friendly", "high_protein"],
    [
      ["Kidney Beans", 70, "g"],
      ["Onion", 60, "g"],
      ["Tomato", 70, "g"],
      ["Garlic", 6, "g"],
      ["Ginger", 5, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Soak kidney beans",
          480,
          "Soak rajma in water for at least 8 hours (overnight).",
        ],
      ],
      pairings: [["Steamed Rice", "rice_pairing"]],
    },
  ),

  d(
    "Chole Masala",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    35,
    "medium",
    "spicy",
    ["leftover_friendly", "batch_cook_friendly", "high_protein"],
    [
      ["Chickpeas", 70, "g"],
      ["Onion", 60, "g"],
      ["Tomato", 70, "g"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Chaat Masala", 1, "tsp"],
      ["Coriander Powder", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [["Soak chickpeas", 480, "Soak kabuli chana overnight (8h)."]],
      pairings: [["Bhature", "bread_pairing"]],
    },
  ),

  d(
    "Palak Paneer",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    15,
    25,
    "medium",
    "medium",
    ["kid_friendly", "high_protein", "low_carb"],
    [
      ["Spinach", 150, "g"],
      ["Paneer", 80, "g"],
      ["Onion", 40, "g"],
      ["Garlic", 6, "g"],
      ["Tomato", 40, "g"],
      ["Fresh Cream", 20, "ml", false],
      ["Garam Masala", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Tandoori Roti", "bread_pairing"]] },
  ),

  d(
    "Paneer Butter Masala",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    15,
    25,
    "medium",
    "mild",
    ["kid_friendly", "high_protein"],
    [
      ["Paneer", 90, "g"],
      ["Tomato", 90, "g"],
      ["Butter", 15, "g"],
      ["Fresh Cream", 25, "ml"],
      ["Cashews", 15, "g"],
      ["Garlic", 5, "g"],
      ["Ginger", 5, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Butter Naan", "bread_pairing"]] },
  ),

  d(
    "Aloo Gobi",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    10,
    25,
    "easy",
    "medium",
    ["leftover_friendly", "lunchbox_friendly"],
    [
      ["Potato", 100, "g"],
      ["Cauliflower", 120, "g"],
      ["Onion", 40, "g"],
      ["Tomato", 40, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Cumin Seeds", 1, "tsp"],
      ["Coriander Powder", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Bhindi Masala",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    10,
    20,
    "easy",
    "medium",
    ["lunchbox_friendly", "low_carb"],
    [
      ["Okra", 150, "g"],
      ["Onion", 50, "g"],
      ["Tomato", 40, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Coriander Powder", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Baingan Bharta",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    25,
    "medium",
    "medium",
    ["low_carb", "diabetic_friendly"],
    [
      ["Eggplant", 200, "g"],
      ["Onion", 50, "g"],
      ["Tomato", 50, "g"],
      ["Garlic", 6, "g"],
      ["Green Chili", 5, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Mustard Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Kadhi Pakora",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    20,
    30,
    "medium",
    "medium",
    ["leftover_friendly"],
    [
      ["Gram Flour", 50, "g"],
      ["Yogurt", 120, "g"],
      ["Onion", 40, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Cumin Seeds", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Matar Paneer",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    15,
    25,
    "medium",
    "medium",
    ["kid_friendly", "high_protein"],
    [
      ["Paneer", 80, "g"],
      ["Green Peas", 60, "g"],
      ["Tomato", 70, "g"],
      ["Onion", 50, "g"],
      ["Ginger", 5, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Dal Makhani",
    "Punjabi",
    "vegetarian",
    ["lunch", "dinner"],
    20,
    60,
    "hard",
    "mild",
    [
      "kid_friendly",
      "leftover_friendly",
      "batch_cook_friendly",
      "high_protein",
    ],
    [
      ["Urad Dal", 50, "g"],
      ["Kidney Beans", 25, "g"],
      ["Butter", 15, "g"],
      ["Fresh Cream", 25, "ml"],
      ["Tomato", 60, "g"],
      ["Garlic", 6, "g"],
      ["Ginger", 5, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Soak dal and beans",
          480,
          "Soak whole urad and rajma overnight (8h).",
        ],
      ],
      pairings: [["Butter Naan", "bread_pairing"]],
    },
  ),

  d(
    "Kala Chana Masala",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    30,
    "medium",
    "medium",
    ["leftover_friendly", "high_protein", "diabetic_friendly"],
    [
      ["Black Chickpeas", 70, "g"],
      ["Onion", 50, "g"],
      ["Tomato", 60, "g"],
      ["Ginger", 5, "g"],
      ["Coriander Powder", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        ["Soak black chickpeas", 480, "Soak kala chana overnight (8h)."],
      ],
    },
  ),

  d(
    "Aloo Matar",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    10,
    25,
    "easy",
    "medium",
    ["kid_friendly", "leftover_friendly", "lunchbox_friendly"],
    [
      ["Potato", 100, "g"],
      ["Green Peas", 60, "g"],
      ["Tomato", 60, "g"],
      ["Onion", 40, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Cumin Seeds", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Jeera Aloo",
    "North Indian",
    "vegan",
    ["lunch", "dinner", "breakfast"],
    5,
    15,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly"],
    [
      ["Potato", 150, "g"],
      ["Cumin Seeds", 1.5, "tsp"],
      ["Turmeric", 0.5, "tsp"],
      ["Green Chili", 4, "g"],
      ["Coriander Leaves", 8, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Shahi Paneer",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    15,
    25,
    "medium",
    "mild",
    ["kid_friendly", "high_protein"],
    [
      ["Paneer", 90, "g"],
      ["Cashews", 18, "g"],
      ["Fresh Cream", 25, "ml"],
      ["Tomato", 70, "g"],
      ["Onion", 40, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  // ── Rice & breads ────────────────────────────────────────────────────────────
  d(
    "Steamed Rice",
    "Indian",
    "vegan",
    ["lunch", "dinner"],
    5,
    15,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly", "batch_cook_friendly", "low_sodium"],
    [
      ["Rice", 80, "g"],
      ["Salt", 0.25, "tsp", false],
    ],
  ),

  d(
    "Jeera Rice",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    5,
    20,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly", "lunchbox_friendly"],
    [
      ["Basmati Rice", 80, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Roti",
    "Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    10,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly", "low_sodium"],
    [
      ["Wheat Flour", 60, "g"],
      ["Salt", 0.25, "tsp", false],
      ["Cooking Oil", 0.5, "tsp", false],
    ],
  ),

  d(
    "Tandoori Roti",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    10,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly"],
    [
      ["Wheat Flour", 65, "g"],
      ["Salt", 0.25, "tsp"],
      ["Cooking Oil", 0.5, "tsp", false],
    ],
  ),

  d(
    "Butter Naan",
    "Punjabi",
    "vegetarian",
    ["lunch", "dinner"],
    90,
    10,
    "medium",
    "mild",
    ["kid_friendly"],
    [
      ["Refined Flour", 70, "g"],
      ["Yogurt", 25, "g"],
      ["Butter", 8, "g"],
      ["Baking Soda", 0.25, "tsp"],
      ["Salt", 0.25, "tsp"],
    ],
    {
      prepTasks: [
        ["Rest the dough", 90, "Let the naan dough proof for ~90 minutes."],
      ],
    },
  ),

  d(
    "Bhature",
    "Punjabi",
    "vegetarian",
    ["lunch", "breakfast"],
    120,
    15,
    "medium",
    "mild",
    ["kid_friendly"],
    [
      ["Refined Flour", 80, "g"],
      ["Yogurt", 25, "g"],
      ["Baking Soda", 0.25, "tsp"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.25, "tsp"],
    ],
    {
      prepTasks: [
        ["Rest the dough", 120, "Ferment/rest the bhatura dough for ~2 hours."],
      ],
    },
  ),

  d(
    "Aloo Paratha",
    "Punjabi",
    "vegetarian",
    ["breakfast", "lunch"],
    20,
    15,
    "medium",
    "medium",
    ["kid_friendly", "lunchbox_friendly", "leftover_friendly"],
    [
      ["Wheat Flour", 70, "g"],
      ["Potato", 100, "g"],
      ["Green Chili", 4, "g"],
      ["Coriander Leaves", 8, "g"],
      ["Ghee", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
    { pairings: [["Boondi Raita", "condiment"]] },
  ),

  d(
    "Veg Pulao",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    25,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly", "leftover_friendly"],
    [
      ["Basmati Rice", 80, "g"],
      ["Carrot", 30, "g"],
      ["Green Peas", 30, "g"],
      ["French Beans", 30, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Garam Masala", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Vegetable Biryani",
    "Hyderabadi",
    "vegetarian",
    ["lunch", "dinner"],
    30,
    40,
    "hard",
    "spicy",
    ["batch_cook_friendly", "leftover_friendly"],
    [
      ["Basmati Rice", 90, "g"],
      ["Cauliflower", 50, "g"],
      ["Carrot", 40, "g"],
      ["Green Peas", 30, "g"],
      ["Yogurt", 40, "g"],
      ["Onion", 60, "g"],
      ["Garam Masala", 1.5, "tsp"],
      ["Saffron", 1, "pinch"],
      ["Ghee", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Marinate the vegetables",
          60,
          "Marinate veg in spiced yogurt for an hour.",
        ],
      ],
      pairings: [["Boondi Raita", "condiment"]],
    },
  ),

  // ── South Indian ──────────────────────────────────────────────────────────────
  d(
    "Idli",
    "South Indian",
    "vegan",
    ["breakfast", "snack"],
    5,
    20,
    "medium",
    "mild",
    ["kid_friendly", "leftover_friendly", "low_sodium", "low_carb"],
    [
      ["Idli Rice", 70, "g"],
      ["Urad Dal", 25, "g"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Soak and ferment batter",
          720,
          "Soak rice + dal, grind, and ferment 8-12h.",
        ],
      ],
      pairings: [
        ["Coconut Chutney", "condiment"],
        ["Sambar", "main_side"],
      ],
    },
  ),

  d(
    "Masala Dosa",
    "South Indian",
    "vegan",
    ["breakfast", "dinner"],
    15,
    20,
    "medium",
    "medium",
    ["kid_friendly", "leftover_friendly"],
    [
      ["Idli Rice", 70, "g"],
      ["Urad Dal", 25, "g"],
      ["Potato", 90, "g"],
      ["Onion", 40, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Curry Leaves", 3, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Ferment dosa batter",
          720,
          "Ferment the ground batter overnight (8-12h).",
        ],
      ],
      pairings: [
        ["Coconut Chutney", "condiment"],
        ["Sambar", "main_side"],
      ],
    },
  ),

  d(
    "Plain Dosa",
    "South Indian",
    "vegan",
    ["breakfast", "dinner"],
    10,
    15,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly"],
    [
      ["Idli Rice", 70, "g"],
      ["Urad Dal", 25, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Ferment dosa batter",
          720,
          "Ferment the ground batter overnight (8-12h).",
        ],
      ],
      pairings: [["Coconut Chutney", "condiment"]],
    },
  ),

  d(
    "Medu Vada",
    "South Indian",
    "vegan",
    ["breakfast", "snack"],
    20,
    20,
    "medium",
    "medium",
    [],
    [
      ["Urad Dal", 60, "g"],
      ["Green Chili", 4, "g"],
      ["Curry Leaves", 3, "g"],
      ["Black Pepper", 0.5, "tsp"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Soak urad dal", 240, "Soak urad dal for ~4 hours before grinding."],
      ],
      pairings: [["Coconut Chutney", "condiment"]],
    },
  ),

  d(
    "Sambar",
    "South Indian",
    "vegan",
    ["lunch", "dinner"],
    15,
    30,
    "medium",
    "medium",
    ["leftover_friendly", "batch_cook_friendly", "high_protein"],
    [
      ["Toor Dal", 50, "g"],
      ["Drumstick", 50, "g"],
      ["Tomato", 40, "g"],
      ["Tamarind", 10, "g"],
      ["Sambar Powder", 1.5, "tsp"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Curry Leaves", 3, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Rasam",
    "South Indian",
    "vegan",
    ["lunch", "dinner"],
    10,
    20,
    "easy",
    "spicy",
    ["leftover_friendly", "low_carb"],
    [
      ["Toor Dal", 30, "g"],
      ["Tomato", 60, "g"],
      ["Tamarind", 10, "g"],
      ["Rasam Powder", 1.5, "tsp"],
      ["Garlic", 5, "g"],
      ["Curry Leaves", 3, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Cooking Oil", 1, "tsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Coconut Chutney",
    "South Indian",
    "vegan",
    ["breakfast", "snack"],
    10,
    5,
    "easy",
    "mild",
    ["low_carb"],
    [
      ["Grated Coconut", 60, "g"],
      ["Green Chili", 4, "g"],
      ["Curry Leaves", 3, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Urad Dal", 5, "g"],
      ["Cooking Oil", 1, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Lemon Rice",
    "South Indian",
    "vegan",
    ["lunch", "breakfast"],
    10,
    15,
    "easy",
    "medium",
    ["lunchbox_friendly", "leftover_friendly"],
    [
      ["Rice", 80, "g"],
      ["Lemon", 0.5, "piece"],
      ["Peanuts", 15, "g"],
      ["Curry Leaves", 3, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Turmeric", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Curd Rice",
    "South Indian",
    "vegetarian",
    ["lunch", "dinner"],
    10,
    15,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly", "low_sodium"],
    [
      ["Rice", 80, "g"],
      ["Yogurt", 120, "g"],
      ["Curry Leaves", 3, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Green Chili", 3, "g"],
      ["Cooking Oil", 1, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Upma",
    "South Indian",
    "vegan",
    ["breakfast"],
    10,
    15,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly"],
    [
      ["Semolina", 70, "g"],
      ["Onion", 40, "g"],
      ["Green Chili", 4, "g"],
      ["Curry Leaves", 3, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Ven Pongal",
    "South Indian",
    "vegetarian",
    ["breakfast"],
    10,
    25,
    "easy",
    "mild",
    ["kid_friendly", "high_protein", "leftover_friendly"],
    [
      ["Rice", 60, "g"],
      ["Moong Dal", 30, "g"],
      ["Black Pepper", 0.5, "tsp"],
      ["Cumin Seeds", 1, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Curry Leaves", 3, "g"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Uttapam",
    "South Indian",
    "vegan",
    ["breakfast", "dinner"],
    10,
    20,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly"],
    [
      ["Idli Rice", 70, "g"],
      ["Urad Dal", 25, "g"],
      ["Onion", 40, "g"],
      ["Tomato", 40, "g"],
      ["Green Chili", 4, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
    {
      prepTasks: [
        ["Ferment batter", 720, "Ferment dosa-style batter overnight."],
      ],
    },
  ),

  d(
    "Rava Dosa",
    "South Indian",
    "vegan",
    ["breakfast", "dinner"],
    15,
    15,
    "medium",
    "medium",
    ["leftover_friendly"],
    [
      ["Semolina", 50, "g"],
      ["Rice Flour", 30, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Green Chili", 4, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Bisi Bele Bath",
    "South Indian",
    "vegetarian",
    ["lunch", "dinner"],
    15,
    35,
    "medium",
    "spicy",
    ["batch_cook_friendly", "leftover_friendly", "high_protein"],
    [
      ["Rice", 60, "g"],
      ["Toor Dal", 40, "g"],
      ["Carrot", 30, "g"],
      ["Green Peas", 30, "g"],
      ["Tamarind", 8, "g"],
      ["Sambar Powder", 1.5, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Cashews", 10, "g"],
      ["Salt", 1, "tsp"],
    ],
  ),

  // ── West India (Gujarati / Maharashtrian) ───────────────────────────────────��─
  d(
    "Dhokla",
    "Gujarati",
    "vegetarian",
    ["breakfast", "snack"],
    20,
    20,
    "medium",
    "mild",
    ["kid_friendly", "low_sodium"],
    [
      ["Gram Flour", 70, "g"],
      ["Yogurt", 40, "g"],
      ["Green Chili", 4, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Baking Soda", 0.5, "tsp"],
      ["Curry Leaves", 3, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Rest the batter",
          30,
          "Let the besan batter rest ~30 minutes before steaming.",
        ],
      ],
    },
  ),

  d(
    "Khandvi",
    "Gujarati",
    "vegetarian",
    ["snack"],
    15,
    20,
    "hard",
    "mild",
    ["low_carb"],
    [
      ["Gram Flour", 60, "g"],
      ["Yogurt", 60, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Curry Leaves", 3, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Thepla",
    "Gujarati",
    "vegetarian",
    ["breakfast", "lunch"],
    15,
    15,
    "easy",
    "medium",
    ["lunchbox_friendly", "leftover_friendly", "batch_cook_friendly"],
    [
      ["Wheat Flour", 70, "g"],
      ["Fenugreek Leaves", 30, "g"],
      ["Yogurt", 20, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Red Chili Powder", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Undhiyu",
    "Gujarati",
    "vegan",
    ["lunch", "dinner"],
    30,
    40,
    "hard",
    "medium",
    ["batch_cook_friendly"],
    [
      ["Eggplant", 60, "g"],
      ["Potato", 60, "g"],
      ["Raw Banana", 60, "g"],
      ["French Beans", 50, "g"],
      ["Green Peas", 40, "g"],
      ["Grated Coconut", 20, "g"],
      ["Coriander Leaves", 10, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Poha",
    "Maharashtrian",
    "vegan",
    ["breakfast"],
    10,
    10,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly", "low_sodium"],
    [
      ["Flattened Rice", 70, "g"],
      ["Onion", 40, "g"],
      ["Potato", 40, "g"],
      ["Peanuts", 15, "g"],
      ["Green Chili", 4, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Curry Leaves", 3, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Sabudana Khichdi",
    "Maharashtrian",
    "vegan",
    ["breakfast", "snack"],
    10,
    15,
    "easy",
    "mild",
    ["kid_friendly"],
    [
      ["Sago", 70, "g"],
      ["Peanuts", 20, "g"],
      ["Potato", 50, "g"],
      ["Green Chili", 4, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Soak sago", 480, "Soak sabudana for 6-8 hours until soft."],
      ],
    },
  ),

  d(
    "Misal Pav",
    "Maharashtrian",
    "vegetarian",
    ["breakfast", "lunch"],
    20,
    30,
    "medium",
    "spicy",
    ["high_protein", "batch_cook_friendly"],
    [
      ["Moong Sprouts", 90, "g"],
      ["Onion", 50, "g"],
      ["Tomato", 50, "g"],
      ["Garlic", 6, "g"],
      ["Pav Bhaji Masala", 1.5, "tsp"],
      ["Pav", 2, "piece"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Pav Bhaji",
    "Maharashtrian",
    "vegetarian",
    ["dinner", "snack"],
    15,
    25,
    "medium",
    "medium",
    ["kid_friendly", "leftover_friendly"],
    [
      ["Potato", 90, "g"],
      ["Cauliflower", 50, "g"],
      ["Green Peas", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Tomato", 80, "g"],
      ["Butter", 15, "g"],
      ["Pav Bhaji Masala", 2, "tsp"],
      ["Pav", 2, "piece"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Vada Pav",
    "Maharashtrian",
    "vegetarian",
    ["snack"],
    15,
    20,
    "easy",
    "spicy",
    ["kid_friendly"],
    [
      ["Potato", 100, "g"],
      ["Gram Flour", 40, "g"],
      ["Pav", 1, "piece"],
      ["Garlic", 6, "g"],
      ["Green Chili", 5, "g"],
      ["Mustard Seeds", 0.5, "tsp"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Dal Dhokli",
    "Gujarati",
    "vegetarian",
    ["lunch", "dinner"],
    20,
    30,
    "medium",
    "medium",
    ["leftover_friendly", "high_protein"],
    [
      ["Toor Dal", 50, "g"],
      ["Wheat Flour", 40, "g"],
      ["Tomato", 40, "g"],
      ["Jaggery", 10, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Peanuts", 10, "g"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Pithla",
    "Maharashtrian",
    "vegan",
    ["lunch", "dinner"],
    10,
    15,
    "easy",
    "medium",
    ["leftover_friendly"],
    [
      ["Gram Flour", 60, "g"],
      ["Onion", 40, "g"],
      ["Garlic", 5, "g"],
      ["Green Chili", 4, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Curry Leaves", 3, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  // ── Jain (no onion / garlic) ────────────────────────────────────────────────��─
  d(
    "Jain Paneer Bhurji",
    "North Indian",
    "jain",
    ["lunch", "dinner", "breakfast"],
    10,
    15,
    "easy",
    "medium",
    ["high_protein", "low_carb", "kid_friendly"],
    [
      ["Paneer", 100, "g"],
      ["Tomato", 60, "g"],
      ["Capsicum", 40, "g"],
      ["Green Chili", 4, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Garam Masala", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Jain Dal Fry",
    "North Indian",
    "jain",
    ["lunch", "dinner"],
    10,
    25,
    "easy",
    "medium",
    ["leftover_friendly", "high_protein"],
    [
      ["Toor Dal", 60, "g"],
      ["Tomato", 50, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Turmeric", 0.5, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Asafoetida", 1, "pinch"],
      ["Coriander Leaves", 8, "g"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Jain Vegetable Pulao",
    "North Indian",
    "jain",
    ["lunch", "dinner"],
    15,
    25,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly"],
    [
      ["Basmati Rice", 80, "g"],
      ["Carrot", 30, "g"],
      ["Green Peas", 30, "g"],
      ["Capsicum", 30, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Garam Masala", 0.5, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Cashews", 10, "g"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Jain Pav Bhaji",
    "Maharashtrian",
    "jain",
    ["dinner", "snack"],
    15,
    25,
    "medium",
    "medium",
    ["kid_friendly"],
    [
      ["Raw Banana", 80, "g"],
      ["Green Peas", 50, "g"],
      ["Capsicum", 40, "g"],
      ["Tomato", 80, "g"],
      ["Butter", 15, "g"],
      ["Pav Bhaji Masala", 2, "tsp"],
      ["Pav", 2, "piece"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Jain Samosa",
    "North Indian",
    "jain",
    ["snack"],
    25,
    20,
    "medium",
    "medium",
    ["kid_friendly"],
    [
      ["Refined Flour", 60, "g"],
      ["Green Peas", 70, "g"],
      ["Green Chili", 4, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Coriander Powder", 1, "tsp"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  // ── Snacks & chaat ────────────────────────────────────────────────────────────
  d(
    "Samosa",
    "North Indian",
    "vegan",
    ["snack"],
    25,
    20,
    "medium",
    "medium",
    ["kid_friendly"],
    [
      ["Refined Flour", 60, "g"],
      ["Potato", 90, "g"],
      ["Green Peas", 30, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Coriander Powder", 1, "tsp"],
      ["Green Chili", 4, "g"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    { pairings: [["Mint Chutney", "condiment"]] },
  ),

  d(
    "Onion Pakora",
    "North Indian",
    "vegan",
    ["snack"],
    10,
    15,
    "easy",
    "medium",
    ["kid_friendly"],
    [
      ["Gram Flour", 60, "g"],
      ["Onion", 80, "g"],
      ["Green Chili", 4, "g"],
      ["Carom Seeds", 0.5, "tsp"],
      ["Red Chili Powder", 0.5, "tsp"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    { pairings: [["Mint Chutney", "condiment"]] },
  ),

  d(
    "Aloo Tikki",
    "North Indian",
    "vegan",
    ["snack"],
    15,
    15,
    "easy",
    "medium",
    ["kid_friendly"],
    [
      ["Potato", 120, "g"],
      ["Green Peas", 30, "g"],
      ["Bread", 1, "slice"],
      ["Cumin Seeds", 1, "tsp"],
      ["Green Chili", 4, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    { pairings: [["Mint Chutney", "condiment"]] },
  ),

  d(
    "Bhel Puri",
    "Maharashtrian",
    "vegan",
    ["snack"],
    10,
    0,
    "easy",
    "medium",
    ["low_sodium"],
    [
      ["Puffed Rice", 50, "g"],
      ["Onion", 30, "g"],
      ["Tomato", 30, "g"],
      ["Tamarind", 8, "g"],
      ["Green Chili", 3, "g"],
      ["Coriander Leaves", 8, "g"],
      ["Chaat Masala", 1, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Pani Puri",
    "North Indian",
    "vegan",
    ["snack"],
    20,
    10,
    "medium",
    "spicy",
    [],
    [
      ["Refined Flour", 40, "g"],
      ["Semolina", 30, "g"],
      ["Potato", 60, "g"],
      ["Mint Leaves", 20, "g"],
      ["Tamarind", 10, "g"],
      ["Chaat Masala", 1, "tsp"],
      ["Black Salt", 0.5, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Mint Chutney",
    "Indian",
    "vegan",
    ["snack"],
    10,
    0,
    "easy",
    "spicy",
    ["low_carb", "low_sodium"],
    [
      ["Mint Leaves", 30, "g"],
      ["Coriander Leaves", 20, "g"],
      ["Green Chili", 5, "g"],
      ["Lemon", 0.5, "piece"],
      ["Cumin Seeds", 0.5, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Masala Peanuts",
    "Indian",
    "vegan",
    ["snack"],
    10,
    10,
    "easy",
    "spicy",
    ["high_protein", "low_carb"],
    [
      ["Peanuts", 60, "g"],
      ["Gram Flour", 25, "g"],
      ["Red Chili Powder", 0.5, "tsp"],
      ["Turmeric", 0.25, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Hara Bhara Kabab",
    "North Indian",
    "vegetarian",
    ["snack", "dinner"],
    20,
    15,
    "medium",
    "mild",
    ["kid_friendly", "high_protein"],
    [
      ["Spinach", 80, "g"],
      ["Green Peas", 50, "g"],
      ["Potato", 60, "g"],
      ["Paneer", 30, "g"],
      ["Green Chili", 4, "g"],
      ["Cornflour", 15, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Paneer Tikka",
    "North Indian",
    "vegetarian",
    ["snack", "dinner"],
    20,
    15,
    "medium",
    "medium",
    ["high_protein", "low_carb", "kid_friendly"],
    [
      ["Paneer", 120, "g"],
      ["Yogurt", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Onion", 40, "g"],
      ["Tandoori Masala", 1.5, "tsp"],
      ["Ginger", 4, "g"],
      ["Garlic", 5, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Marinate the paneer",
          120,
          "Marinate paneer in spiced yogurt for ~2 hours.",
        ],
      ],
    },
  ),

  d(
    "Boondi Raita",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    10,
    0,
    "easy",
    "mild",
    ["kid_friendly", "low_carb"],
    [
      ["Yogurt", 120, "g"],
      ["Gram Flour", 20, "g"],
      ["Cumin Seeds", 0.5, "tsp"],
      ["Black Salt", 0.25, "tsp"],
      ["Red Chili Powder", 0.25, "tsp"],
      ["Salt", 0.25, "tsp"],
    ],
  ),

  // ── Eggetarian ────────────────────────────────────────────────────────────────
  d(
    "Masala Omelette",
    "Indian",
    "eggetarian",
    ["breakfast"],
    5,
    10,
    "easy",
    "medium",
    ["kid_friendly", "high_protein", "low_carb"],
    [
      ["Egg", 2, "piece"],
      ["Onion", 30, "g"],
      ["Tomato", 30, "g"],
      ["Green Chili", 4, "g"],
      ["Coriander Leaves", 6, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Egg Bhurji",
    "Indian",
    "eggetarian",
    ["breakfast", "dinner"],
    5,
    10,
    "easy",
    "medium",
    ["high_protein", "low_carb", "kid_friendly"],
    [
      ["Egg", 2, "piece"],
      ["Onion", 40, "g"],
      ["Tomato", 40, "g"],
      ["Green Chili", 4, "g"],
      ["Turmeric", 0.25, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Egg Curry",
    "North Indian",
    "eggetarian",
    ["lunch", "dinner"],
    10,
    25,
    "medium",
    "medium",
    ["high_protein", "leftover_friendly"],
    [
      ["Egg", 2, "piece"],
      ["Onion", 60, "g"],
      ["Tomato", 70, "g"],
      ["Garlic", 6, "g"],
      ["Ginger", 5, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Bread Omelette",
    "Indian",
    "eggetarian",
    ["breakfast"],
    5,
    10,
    "easy",
    "mild",
    ["kid_friendly", "high_protein"],
    [
      ["Egg", 2, "piece"],
      ["Bread", 2, "slice"],
      ["Onion", 30, "g"],
      ["Green Chili", 3, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Egg Fried Rice",
    "Indo-Chinese",
    "eggetarian",
    ["lunch", "dinner"],
    10,
    15,
    "easy",
    "medium",
    ["kid_friendly", "high_protein", "leftover_friendly"],
    [
      ["Rice", 90, "g"],
      ["Egg", 2, "piece"],
      ["Spring Onion", 30, "g"],
      ["Carrot", 30, "g"],
      ["Capsicum", 30, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Shakshuka",
    "Mediterranean",
    "eggetarian",
    ["breakfast", "dinner"],
    10,
    20,
    "easy",
    "medium",
    ["high_protein", "low_carb"],
    [
      ["Egg", 2, "piece"],
      ["Tomato", 120, "g"],
      ["Onion", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Garlic", 6, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  // ── Non-vegetarian (poultry / red meat) ────────────────────────────────────��─
  d(
    "Butter Chicken",
    "Punjabi",
    "non_vegetarian",
    ["dinner"],
    30,
    30,
    "hard",
    "mild",
    ["kid_friendly", "high_protein"],
    [
      ["Chicken", 150, "g"],
      ["Tomato", 90, "g"],
      ["Butter", 15, "g"],
      ["Fresh Cream", 25, "ml"],
      ["Cashews", 12, "g"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Tandoori Masala", 1, "tsp"],
      ["Garam Masala", 1, "tsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Marinate the chicken",
          240,
          "Marinate chicken in yogurt + spices ~4 hours.",
        ],
      ],
      pairings: [["Butter Naan", "bread_pairing"]],
    },
  ),

  d(
    "Chicken Curry",
    "Indian",
    "non_vegetarian",
    ["lunch", "dinner"],
    15,
    35,
    "medium",
    "spicy",
    ["high_protein", "leftover_friendly", "batch_cook_friendly"],
    [
      ["Chicken", 150, "g"],
      ["Onion", 70, "g"],
      ["Tomato", 70, "g"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Garam Masala", 1.5, "tsp"],
      ["Turmeric", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Chicken Biryani",
    "Hyderabadi",
    "non_vegetarian",
    ["lunch", "dinner"],
    30,
    45,
    "hard",
    "spicy",
    ["batch_cook_friendly", "high_protein", "leftover_friendly"],
    [
      ["Basmati Rice", 90, "g"],
      ["Chicken", 130, "g"],
      ["Yogurt", 50, "g"],
      ["Onion", 70, "g"],
      ["Garam Masala", 1.5, "tsp"],
      ["Saffron", 1, "pinch"],
      ["Mint Leaves", 10, "g"],
      ["Ghee", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Marinate the chicken",
          120,
          "Marinate chicken in spiced yogurt ~2 hours.",
        ],
      ],
      pairings: [["Boondi Raita", "condiment"]],
    },
  ),

  d(
    "Tandoori Chicken",
    "Punjabi",
    "non_vegetarian",
    ["dinner", "snack"],
    20,
    30,
    "medium",
    "spicy",
    ["high_protein", "low_carb"],
    [
      ["Chicken", 180, "g"],
      ["Yogurt", 50, "g"],
      ["Tandoori Masala", 2, "tsp"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Lemon", 0.5, "piece"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Marinate the chicken",
          240,
          "Marinate chicken in yogurt + tandoori masala ~4 hours.",
        ],
      ],
    },
  ),

  d(
    "Chicken Tikka",
    "Punjabi",
    "non_vegetarian",
    ["snack", "dinner"],
    20,
    20,
    "medium",
    "medium",
    ["high_protein", "low_carb"],
    [
      ["Chicken", 160, "g"],
      ["Yogurt", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Onion", 40, "g"],
      ["Tandoori Masala", 1.5, "tsp"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Marinate the chicken", 180, "Marinate chicken ~3 hours for tikka."],
      ],
    },
  ),

  d(
    "Mutton Rogan Josh",
    "Kashmiri",
    "non_vegetarian",
    ["lunch", "dinner"],
    20,
    75,
    "hard",
    "spicy",
    ["high_protein", "batch_cook_friendly", "leftover_friendly"],
    [
      ["Mutton", 160, "g"],
      ["Yogurt", 50, "g"],
      ["Onion", 70, "g"],
      ["Garlic", 7, "g"],
      ["Ginger", 6, "g"],
      ["Garam Masala", 1.5, "tsp"],
      ["Red Chili Powder", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Marinate the mutton",
          120,
          "Marinate mutton in yogurt + spices ~2 hours.",
        ],
      ],
      pairings: [["Steamed Rice", "rice_pairing"]],
    },
  ),

  d(
    "Keema Matar",
    "North Indian",
    "non_vegetarian",
    ["lunch", "dinner"],
    15,
    35,
    "medium",
    "spicy",
    ["high_protein", "leftover_friendly"],
    [
      ["Mutton", 150, "g"],
      ["Green Peas", 50, "g"],
      ["Onion", 60, "g"],
      ["Tomato", 60, "g"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Garam Masala", 1.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Chicken 65",
    "South Indian",
    "non_vegetarian",
    ["snack", "dinner"],
    15,
    20,
    "medium",
    "spicy",
    ["high_protein"],
    [
      ["Chicken", 160, "g"],
      ["Yogurt", 30, "g"],
      ["Cornflour", 20, "g"],
      ["Curry Leaves", 4, "g"],
      ["Red Chili Powder", 1.5, "tsp"],
      ["Ginger", 5, "g"],
      ["Garlic", 6, "g"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Marinate the chicken", 60, "Marinate chicken ~1 hour before frying."],
      ],
    },
  ),

  d(
    "Chilli Chicken",
    "Indo-Chinese",
    "non_vegetarian",
    ["dinner", "snack"],
    15,
    20,
    "medium",
    "spicy",
    ["high_protein"],
    [
      ["Chicken", 160, "g"],
      ["Capsicum", 50, "g"],
      ["Onion", 50, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Cornflour", 20, "g"],
      ["Garlic", 6, "g"],
      ["Green Chili", 5, "g"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  // ── Pescatarian (fish / shellfish) ──────────────────────────────────────────��─
  d(
    "Fish Curry",
    "Bengali",
    "pescatarian",
    ["lunch", "dinner"],
    15,
    25,
    "medium",
    "spicy",
    ["high_protein", "leftover_friendly"],
    [
      ["Fish", 150, "g"],
      ["Onion", 60, "g"],
      ["Tomato", 60, "g"],
      ["Tamarind", 8, "g"],
      ["Garlic", 6, "g"],
      ["Ginger", 5, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Coconut Milk", 60, "ml"],
      ["Mustard Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Fish Fry",
    "Coastal",
    "pescatarian",
    ["lunch", "snack"],
    15,
    15,
    "easy",
    "spicy",
    ["high_protein"],
    [
      ["Pomfret", 180, "g"],
      ["Semolina", 30, "g"],
      ["Rice Flour", 20, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Red Chili Powder", 1, "tsp"],
      ["Lemon", 0.5, "piece"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Marinate the fish", 60, "Marinate fish in lemon + spices ~1 hour."],
      ],
    },
  ),

  d(
    "Prawn Masala",
    "Coastal",
    "pescatarian",
    ["lunch", "dinner"],
    15,
    20,
    "medium",
    "spicy",
    ["high_protein", "low_carb"],
    [
      ["Prawns", 150, "g"],
      ["Onion", 60, "g"],
      ["Tomato", 60, "g"],
      ["Garlic", 7, "g"],
      ["Ginger", 5, "g"],
      ["Garam Masala", 1, "tsp"],
      ["Coconut Milk", 50, "ml"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
  ),

  d(
    "Goan Fish Curry",
    "Goan",
    "pescatarian",
    ["lunch", "dinner"],
    20,
    25,
    "medium",
    "spicy",
    ["high_protein", "leftover_friendly"],
    [
      ["Fish", 150, "g"],
      ["Coconut Milk", 80, "ml"],
      ["Tamarind", 10, "g"],
      ["Onion", 50, "g"],
      ["Garlic", 6, "g"],
      ["Red Chili Powder", 1.5, "tsp"],
      ["Turmeric", 0.5, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Prawn Fried Rice",
    "Indo-Chinese",
    "pescatarian",
    ["lunch", "dinner"],
    15,
    15,
    "easy",
    "medium",
    ["high_protein", "leftover_friendly"],
    [
      ["Rice", 90, "g"],
      ["Prawns", 120, "g"],
      ["Spring Onion", 30, "g"],
      ["Carrot", 30, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Garlic", 6, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  // ── International ───────────────────────────────────────────────────────────��─
  d(
    "Veg Hakka Noodles",
    "Indo-Chinese",
    "vegan",
    ["dinner", "lunch"],
    15,
    15,
    "easy",
    "medium",
    ["kid_friendly", "leftover_friendly"],
    [
      ["Noodles", 90, "g"],
      ["Cabbage", 40, "g"],
      ["Carrot", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Spring Onion", 30, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Garlic", 6, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Veg Manchurian",
    "Indo-Chinese",
    "vegan",
    ["snack", "dinner"],
    20,
    20,
    "medium",
    "spicy",
    ["kid_friendly"],
    [
      ["Cabbage", 80, "g"],
      ["Carrot", 50, "g"],
      ["Capsicum", 30, "g"],
      ["Cornflour", 25, "g"],
      ["Refined Flour", 25, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Garlic", 6, "g"],
      ["Spring Onion", 20, "g"],
      ["Cooking Oil", 2, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Veg Fried Rice",
    "Indo-Chinese",
    "vegan",
    ["lunch", "dinner"],
    10,
    15,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly", "leftover_friendly"],
    [
      ["Rice", 90, "g"],
      ["Carrot", 40, "g"],
      ["French Beans", 30, "g"],
      ["Capsicum", 30, "g"],
      ["Spring Onion", 30, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Margherita Pizza",
    "Italian",
    "vegetarian",
    ["dinner", "snack"],
    90,
    15,
    "medium",
    "mild",
    ["kid_friendly"],
    [
      ["Refined Flour", 100, "g"],
      ["Tomato", 60, "g"],
      ["Cheese", 50, "g"],
      ["Garlic", 4, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Prove the dough", 90, "Let the pizza dough rise ~90 minutes."],
      ],
    },
  ),

  d(
    "Pasta Arrabbiata",
    "Italian",
    "vegan",
    ["dinner", "lunch"],
    10,
    20,
    "easy",
    "spicy",
    ["kid_friendly", "leftover_friendly"],
    [
      ["Pasta", 90, "g"],
      ["Tomato", 120, "g"],
      ["Garlic", 8, "g"],
      ["Dried Red Chili", 2, "piece"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
  ),

  d(
    "Pasta Alfredo",
    "Italian",
    "vegetarian",
    ["dinner", "lunch"],
    10,
    20,
    "easy",
    "mild",
    ["kid_friendly"],
    [
      ["Pasta", 90, "g"],
      ["Fresh Cream", 60, "ml"],
      ["Butter", 15, "g"],
      ["Cheese", 30, "g"],
      ["Garlic", 6, "g"],
      ["Black Pepper", 0.5, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Veg Sandwich",
    "Continental",
    "vegetarian",
    ["breakfast", "snack"],
    10,
    5,
    "easy",
    "mild",
    ["kid_friendly", "lunchbox_friendly"],
    [
      ["Bread", 2, "slice"],
      ["Cucumber", 30, "g"],
      ["Tomato", 30, "g"],
      ["Potato", 40, "g"],
      ["Butter", 8, "g"],
      ["Chaat Masala", 0.5, "tsp"],
      ["Salt", 0.25, "tsp"],
    ],
  ),

  d(
    "Grilled Cheese Sandwich",
    "Continental",
    "vegetarian",
    ["breakfast", "snack"],
    5,
    8,
    "easy",
    "mild",
    ["kid_friendly"],
    [
      ["Bread", 2, "slice"],
      ["Cheese", 40, "g"],
      ["Butter", 10, "g"],
      ["Black Pepper", 0.25, "tsp"],
      ["Salt", 0.25, "tsp"],
    ],
  ),

  d(
    "Veg Burger",
    "Continental",
    "vegetarian",
    ["snack", "dinner"],
    20,
    15,
    "medium",
    "medium",
    ["kid_friendly"],
    [
      ["Pav", 1, "piece"],
      ["Potato", 80, "g"],
      ["Green Peas", 30, "g"],
      ["Bread", 1, "slice"],
      ["Cheese", 20, "g"],
      ["Tomato", 30, "g"],
      ["Cabbage", 20, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Rajma Quinoa Bowl",
    "Fusion",
    "vegan",
    ["lunch", "dinner"],
    15,
    25,
    "easy",
    "mild",
    [
      "high_protein",
      "diabetic_friendly",
      "lunchbox_friendly",
      "leftover_friendly",
    ],
    [
      ["Quinoa", 70, "g"],
      ["Kidney Beans", 60, "g"],
      ["Tomato", 50, "g"],
      ["Onion", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Cumin Seeds", 1, "tsp"],
      ["Lemon", 0.5, "piece"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
    { prepTasks: [["Soak kidney beans", 480, "Soak rajma overnight (8h)."]] },
  ),

  d(
    "Chickpea Salad",
    "Mediterranean",
    "vegan",
    ["lunch", "snack"],
    15,
    0,
    "easy",
    "mild",
    ["high_protein", "low_carb", "diabetic_friendly", "lunchbox_friendly"],
    [
      ["Chickpeas", 80, "g"],
      ["Cucumber", 50, "g"],
      ["Tomato", 50, "g"],
      ["Onion", 30, "g"],
      ["Lemon", 0.5, "piece"],
      ["Coriander Leaves", 8, "g"],
      ["Black Pepper", 0.5, "tsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        ["Soak chickpeas", 480, "Soak chickpeas overnight, then boil."],
      ],
    },
  ),

  d(
    "Tofu Stir Fry",
    "Asian",
    "vegan",
    ["dinner", "lunch"],
    15,
    15,
    "easy",
    "medium",
    ["high_protein", "low_carb", "diabetic_friendly"],
    [
      ["Tofu", 120, "g"],
      ["Capsicum", 40, "g"],
      ["French Beans", 40, "g"],
      ["Carrot", 40, "g"],
      ["Soy Sauce", 1, "tbsp"],
      ["Garlic", 6, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  // Coconut milk matches the engine's non-vegan term "milk" (config.ts), so this
  // is labelled vegetarian for coherence — vegans wouldn't be served it anyway.
  d(
    "Thai Green Curry",
    "Thai",
    "vegetarian",
    ["dinner", "lunch"],
    15,
    25,
    "medium",
    "spicy",
    ["high_protein", "low_carb"],
    [
      ["Coconut Milk", 120, "ml"],
      ["Tofu", 90, "g"],
      ["French Beans", 40, "g"],
      ["Capsicum", 40, "g"],
      ["Green Chili", 6, "g"],
      ["Garlic", 6, "g"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.75, "tsp"],
    ],
    { pairings: [["Steamed Rice", "rice_pairing"]] },
  ),

  d(
    "Hummus",
    "Mediterranean",
    "vegan",
    ["snack"],
    15,
    0,
    "easy",
    "mild",
    ["high_protein", "low_carb"],
    [
      ["Chickpeas", 90, "g"],
      ["Sesame Seeds", 2, "tsp"],
      ["Garlic", 5, "g"],
      ["Lemon", 0.5, "piece"],
      ["Cooking Oil", 1, "tbsp"],
      ["Salt", 0.5, "tsp"],
    ],
    {
      prepTasks: [
        [
          "Soak chickpeas",
          480,
          "Soak chickpeas overnight, then boil until soft.",
        ],
      ],
    },
  ),

  d(
    "Vegetable Soup",
    "Continental",
    "vegan",
    ["dinner", "snack"],
    10,
    20,
    "easy",
    "mild",
    ["low_carb", "low_sodium", "diabetic_friendly"],
    [
      ["Carrot", 50, "g"],
      ["Cabbage", 40, "g"],
      ["French Beans", 40, "g"],
      ["Sweet Corn", 40, "g"],
      ["Tomato", 50, "g"],
      ["Black Pepper", 0.5, "tsp"],
      ["Cornflour", 10, "g"],
      ["Salt", 0.5, "tsp"],
    ],
  ),

  d(
    "Masala Chai",
    "Indian",
    "vegetarian",
    ["breakfast", "snack"],
    5,
    10,
    "easy",
    "mild",
    ["kid_friendly"],
    [
      ["Milk", 120, "ml"],
      ["Tea Leaves", 1, "tsp"],
      ["Sugar", 2, "tsp"],
      ["Ginger", 3, "g"],
      ["Green Cardamom", 1, "piece"],
    ],
  ),

  // ── Required acceptance dishes (BUG-014 "Required seeded dish data") ──────────
  d(
    "Paneer Bhurji",
    "North Indian",
    "vegetarian",
    ["breakfast", "lunch", "dinner"],
    10,
    15,
    "easy",
    "medium",
    ["kid_friendly", "high_protein", "low_carb"],
    [
      ["Paneer", 100, "g"],
      ["Onion", 50, "g"],
      ["Tomato", 50, "g"],
      ["Green Chili", 4, "g"],
      ["Turmeric", 0.5, "tsp"],
      ["Cumin Seeds", 1, "tsp"],
      ["Cooking Oil", 1, "tbsp"],
      ["Coriander Leaves", 10, "g", false],
      ["Salt", 1, "tsp"],
    ],
    {
      desc: "Scrambled paneer cooked with onions, tomatoes and spices.",
      pairings: [["Roti", "bread_pairing"]],
    },
  ),

  d(
    "Khichdi",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    10,
    25,
    "easy",
    "mild",
    ["kid_friendly", "leftover_friendly", "diabetic_friendly"],
    [
      ["Rice", 60, "g"],
      ["Moong Dal", 40, "g"],
      ["Green Peas", 30, "g", false],
      ["Carrot", 30, "g", false],
      ["Turmeric", 0.5, "tsp"],
      ["Cumin Seeds", 1, "tsp"],
      ["Ghee", 1, "tbsp"],
      ["Salt", 1, "tsp"],
    ],
    {
      desc: "A soft one-pot dish of rice and lentils with vegetables.",
      pairings: [["Raita", "condiment"]],
    },
  ),

  d(
    "Mango Pickle",
    "North Indian",
    "vegan",
    ["lunch", "dinner"],
    20,
    0,
    "easy",
    "spicy",
    [],
    [
      ["Raw Mango", 100, "g"],
      ["Mustard Oil", 2, "tbsp"],
      ["Mustard Seeds", 1, "tsp"],
      ["Turmeric", 1, "tsp"],
      ["Red Chili Powder", 1, "tsp"],
      ["Fenugreek Seeds", 0.5, "tsp"],
      ["Asafoetida", 1, "pinch"],
      ["Salt", 2, "tsp"],
    ],
    { desc: "Tangy Indian mango pickle (aam ka achaar) in oil and spices." },
  ),

  d(
    "Papad",
    "Indian",
    "vegan",
    ["lunch", "dinner"],
    2,
    3,
    "easy",
    "mild",
    [],
    [
      ["Urad Dal", 30, "g"],
      ["Cumin Seeds", 0.5, "tsp"],
      ["Black Pepper", 0.5, "tsp"],
      ["Asafoetida", 1, "pinch"],
      ["Salt", 0.5, "tsp"],
    ],
    { desc: "A thin crisp roasted Indian papad." },
  ),

  d(
    "Raita",
    "North Indian",
    "vegetarian",
    ["lunch", "dinner"],
    10,
    0,
    "easy",
    "mild",
    ["kid_friendly", "low_carb", "diabetic_friendly"],
    [
      ["Yogurt", 120, "g"],
      ["Cucumber", 60, "g"],
      ["Cumin Seeds", 0.5, "tsp"],
      ["Black Salt", 0.25, "tsp"],
      ["Coriander Leaves", 5, "g", false],
      ["Salt", 0.25, "tsp"],
    ],
    { desc: "A cooling bowl of Indian yogurt raita with cucumber." },
  ),

  d(
    "Green Salad",
    "Indian",
    "vegan",
    ["lunch", "dinner"],
    10,
    0,
    "easy",
    "mild",
    ["low_carb", "diabetic_friendly"],
    [
      ["Cucumber", 60, "g"],
      ["Tomato", 50, "g"],
      ["Onion", 30, "g"],
      ["Lemon", 0.5, "piece"],
      ["Coriander Leaves", 5, "g", false],
      ["Salt", 0.5, "tsp"],
    ],
    { desc: "A fresh diced salad of cucumber, tomato and onion (kachumber)." },
  ),
];

/**
 * Verified dish images (BUG-014 Phase 6). `name` → `{ url, alt }`, where `url` is
 * a static asset under `public/images/dishes/`. Sourced from openly-licensed
 * Wikimedia Commons photos — see `public/images/CREDITS.md` for per-file author +
 * license. generate.mjs flips these rows to `image_status = 'verified'`,
 * `image_verified = true`; every other dish stays the `placeholder` default.
 */
export const DISH_IMAGES = {
  "Masala Dosa": {
    url: "/images/dishes/masala-dosa.jpg",
    alt: "A crisp golden South Indian masala dosa filled with spiced potato.",
  },
  "Rajma Masala": {
    url: "/images/dishes/rajma.jpg",
    alt: "Red kidney beans simmered in a thick spiced onion-tomato gravy.",
  },
  "Chole Masala": {
    url: "/images/dishes/chole.jpg",
    alt: "Chickpeas cooked in a spiced tomato-onion masala (chole).",
  },
  "Dal Tadka": {
    url: "/images/dishes/dal-tadka.jpg",
    alt: "A bowl of yellow lentils tempered with cumin and spices.",
  },
  "Paneer Bhurji": {
    url: "/images/dishes/paneer-bhurji.jpg",
    alt: "Scrambled paneer cooked with onions, tomatoes and spices.",
  },
  "Aloo Paratha": {
    url: "/images/dishes/paratha.jpg",
    alt: "A pan-cooked stuffed Indian wheat paratha flatbread.",
  },
  Roti: {
    url: "/images/dishes/roti.jpg",
    alt: "A soft round Indian wheat chapati (roti) flatbread.",
  },
  "Jeera Rice": {
    url: "/images/dishes/jeera-rice.jpg",
    alt: "Steamed white rice flavoured with cumin seeds (jeera rice).",
  },
  "Veg Pulao": {
    url: "/images/dishes/vegetable-pulao.jpg",
    alt: "Spiced rice cooked with mixed vegetables (vegetable pulao).",
  },
  Khichdi: {
    url: "/images/dishes/khichdi.jpg",
    alt: "A soft one-pot dish of rice and lentils with vegetables (khichdi).",
  },
  "Egg Curry": {
    url: "/images/dishes/egg-curry.jpg",
    alt: "Boiled eggs simmered in a spiced North Indian curry gravy.",
  },
  "Chicken Curry": {
    url: "/images/dishes/chicken-curry.jpg",
    alt: "Indian chicken curry in a spiced gravy.",
  },
  "Coconut Chutney": {
    url: "/images/dishes/coconut-chutney.jpg",
    alt: "A bowl of white South Indian coconut chutney.",
  },
  "Mint Chutney": {
    url: "/images/dishes/mint-chutney.jpg",
    alt: "A bowl of green mint-coriander chutney.",
  },
  "Mango Pickle": {
    url: "/images/dishes/mango-pickle.jpg",
    alt: "Indian mango pickle (aam ka achaar) in oil and spices.",
  },
  Papad: {
    url: "/images/dishes/papad.jpg",
    alt: "A thin crisp roasted Indian papad (papadum).",
  },
  Raita: {
    url: "/images/dishes/raita.jpg",
    alt: "A bowl of Indian yogurt raita.",
  },
  "Green Salad": {
    url: "/images/dishes/green-salad.jpg",
    alt: "A fresh diced salad of cucumber, tomato and onion (kachumber).",
  },
  "Jeera Aloo": {
    url: "/images/dishes/jeera-aloo.jpg",
    alt: "Diced potatoes sautéed with cumin seeds (jeera aloo).",
  },
};
